### ISSUE TITLE
유연한 Ajax 처리를 위한 코어용 레이아웃 제안

### ISSUE THREAD

**Issue by BootstrapKR** [kimsQ/rb#101]
Rb1.2 에서 Rb2 까지 iframe 처리를 위한 _blank 레이아웃이 기본 제공됩니다.
그런데, Ajax 처리에는 한계가 있는듯 합니다.

예를 들어, 게시판 모듈에서 댓글 처리를 위해 iframe 이 아닌 GET 방식으로 Ajax 사용할 때 입니다.
이 때, 호출 결과를 JSON 등으로 받지 않고 HTML 코드를 그대로 받아서 화면에 뿌려주고자 합니다.

그런데, _blank 레이아웃에는 실제 컨텐츠 외에 ```<html><head></head>...``` 부분까지 모두 들어가게 되므로 사용할 수가 없습니다. (http://.../...&iframe=Y 인 경우)

이렇게 하는 이유는 모듈의 각 테마의 독립성 보장을 위해서입니다.
만약, JSON 등의 메타데이터 형식으로만 처리를 해야한다면 JS 코드에서 실제 UI(HTML 코드)를 코딩해야 하므로, 실제적으로 테마와 모듈간 View <-> Control 분리 및 테마 자체의 개발이 어렵게 되기 때문입니다. 테마는 최대한 손쉽게 .php와 .css만 만들어 사용할 수 있도록 해주어야 할테니까요.
(Ajax건 include건 iframe이건 동일한 결과를 출력)

하나의 예시이고, 쇼핑몰 등을 만들다 보면 메인 화면 등에서 Ajax로 컨텐츠를 탭처리 하는 등 요소요소에 쓰일곳은 많은데, Ajax를 자유롭게 활용할 수 있는 방법이 없는 듯 하여 강력히 제안하는 바입니다.
(제가 모르는 다른 방법이 있다면 알려 주십시요!!!^^)

코어의 변경이 가장 적으면서도 효과적인 방법은 /layouts/_null 레이아웃을 추가해 주는 방법이 있을 것 같습니다.

예를 들어, Ajax 호출을 다음처럼 해줍니다.
- http://..../?r=home&m=xyz&...&ajax=Y

index.php에서 다음처럼 처리해 줍니다.
```
if ($m=='admin' || $iframe=='Y') $d['layout']['php'] = $_HM['layout'] = '_blank/default.php';
else if ($ajax=='Y') $d['layout']['php'] = $_HM['layout'] = '_null/default.php';
else {
```

_null 레이아웃은 다음처럼 구성합니다.
- /layouts/_null/default.php
```
<?php include __KIMS_CONTENT__ ?>
```

- /layouts/_null/_includes/_import.control.php: 빈 파일

이상과 같이 제안합니다.
호출 파라미터나 레이아웃 이름 등은 코어개발팀에서 적절하게 정의해 주시면 될 것 같습니다.

긍정적인 검토 바라겠습니다.
감사합니다.

**Comment by kimsnova** [comment]
sys.js 의 getAjaxData(url) 메소드를 사용하시면 간단히 구현하실 수 있습니다.

ajax 로 받아오려는 페이지의 데이터를 다음과 같이 [RESULT: 와 :RESULT] 로 감싸줍니다.

[RESULT:
리턴할 데이터
:RESULT]

<script>
var ajaxData = getAjaxData('http://.../...&iframe=Y');
$("div").html(ajaxData);
</script>

그리고 위와같이 받아온 후 출력하면 됩니다.
