### ISSUE TITLE
레이아웃 개발자를 위한 레이아웃 설정 관련기능 개선의견 

### ISSUE THREAD

**Issue by BootstrapKR** [kimsQ/rb#105]
레이아웃을 개발하다 보니 겪게되는 어려움이 있습니다.

**1. layouts/MyLayout/_var/_var.config.php 에서 내 레이아웃 정보를 얻을 수 없음**

=> 어디선가 착오가 있었네요... 왜 됬다가 안됬다가 하는듯한 기분이 드는지...^^;;

**2. 파일 선택형 설정기능 필요**

- 파일의 업로드 위치(레이아웃 내)를 _var.config.php에서 설정 시, 사용자가 선택한 파일이 해당 디렉토리 및 파일명으로 업로드 되는 기능
- 예를 들어, 레이아웃에서 사이트의 로고 이미지를 변경할 수 있는 설정기능을 제공하고자 할 때 입니다.

포토셋은 레이아웃에 설치 후 사용할 수 있으므로 레이아웃 초기 구성값을 제공 할 수 없고... 또 기본적으로 이러한 설정 기능과는 어울려 보이지는 않습니다. 

물론, 사용자에게 직접 로고 파일을 FTP 등으로 변경하라고 할 수도 있겠습니다만(다른 CMS도 그러하니까요)... 역시 이런 기능이 없기 때문에 레이아웃 개발에 제약이 많아집니다.

시급한 필수기능은 아니라고 보이지만, 레이아웃 개발을 활성화 하려면 이정도는 지원되는 것이 좋을 것 같습니다. (개인적으로는 반드시 지원되었으면 합니다.)

만약, 이미 지원이 되는 기능이라면 사용법 코멘트좀 부탁드리구요^^
이상 검토 부탁드립니다.

**Comment by kieregh** [comment]
좋은 의견 감사합니다.

관련 이슈에 대한 수정작업이 2.1.0 릴리즈에서 진행되었으며 아래의 링크 참조 부탁드립니다.
https://github.com/kimsQ/rb/issues/80
https://github.com/kimsQ/rb/commit/acf89b8928cd146a1a8fbbf8f2359464517a881a
