### ISSUE TITLE
관리자 접속기록 오류

### ISSUE THREAD

**Issue by taiji88** [kimsQ/rb#106]
관리자의 접속기록을 볼때
리스트에서 이름 클릭해서 모달뜨면 보이는 상세 접속기록 리스트가 나오지 않습니다.

간단히 패치가 가능한 부분인것 같아서
이슈에 남깁니다.

**Comment by kimsnova** [comment]
스위치에서 접속통계 스위치를 활성화하지 않은 것으로 보입니다.
