### ISSUE TITLE
v2.0.0 Release의 How to install

### ISSUE THREAD

**Issue by sevenhopes** [kimsQ/rb#107]
자연스럽게 다듬었습니다.

How to install KimsQ Rb 2.0.0

1. Download rb2-installer.zip below
2. Unpack the file
3. Upload 'rb' folder using FTP client to your server (You can rename the folder)
4. Change the permission of 'rb' folder to 707 including all of its subfolders and files*
5. Open a web browser and type 'http://your-domain/rb'**
6. Follow the steps***
7. Delete '_install' folder after installation finished (optional)

" * Installation cannot be done normally without doing this."
" ** If you already have another version of KimsQ in the root on your server, type 'http://your-domain/rb/index.php' in the address bar."
" *** If you fail the installation with getting through the steps above, unpack and upload rb-2.0.0.zip to the server with changing its permission to 707 and try to browse."

**Comment by gitaeks** [comment]
thanks~

**Comment by sevenhopes** [comment]
각주를 뜻하는 별표(*)가 목록으로 자동 전환 되어 이상하게 보이는 부분이 있어 수정했습니다.
