### ISSUE TITLE
관리자 포토셋에서 타 회원이 업로드한 이미지가 안보이는 문제

### ISSUE THREAD

**Issue by BootstrapKR** [kimsQ/rb#108]
다음의 코드로 문제가 발생합니다.

- /modules/mediaset/modal/modal.photo.media.php

```
	$_WHERE = 'mbruid='.$my['uid'].' and (type=-1 or type=2) and fileonly=0';
```

일반회원도 포토셋 UI를 사용할 수 있도록 지원하실 계획인듯 합니다.
다만, 관리자 모드에서는 mbruid 조건이 빠져야 하지 않을까요?

포토셋의 정확한 용도(개발의도)를 잘못 이해하고 있는지도 모르겠지만...
일반적인 상식으로 관리자는 모든 포토셋을 확인하고 관리할 수 있어야 하지않나 봅니다.

이상 참고해 주세요~

**Comment by kieregh** [comment]
네 안녕하세요..

미디어셋에서 modal 을 통해서 포토/동영상을 삽입하는 상황에서는 그 사용자가 관리자건 
일반 사용자건 자신이 등록한 내용만 나오는 것도 의미가 있다고 생각합니다. 그 상황은 업로드된
내용물을 사용(등록)하는 것이 목적이지 관리하기 위한 것이 아니기 때문입니다.  관리자라고 해도
다른 사람이 올린 사진을 사용할 수는 없다고 보는 것이 일반적이라는 생각입니다.

말씀하신대로, 관리 측면이라면...별도의 리스트 페이지가 존재하고 그 곳에는 모든 등록개체
(포토/영상)가 출력되기 때문에 이 곳에서 할 수 있다고 생각합니다.

요컨대, 제기하신 쿼리문은 정답이 없다고 생각합니다. 사이트 운영방침에 따라서 운영자가 선택해야 
할 문제라고 생각하며 공식적으로 하나의 쿼리에 맞출 필요는 없다고 생각합니다.

따라서 본 이슈는 이렇게 클로징하고자 합니다. 

늘...좋은 의견 감사합니다.
