### ISSUE TITLE
관리자 로그인 불가

### ISSUE THREAD

**Issue by livesam** [kimsQ/rb#109]
![kims2](https://cloud.githubusercontent.com/assets/6669856/5733158/f3ff2704-9be1-11e4-8b4d-f3f77e185c45.png)

로그인 과정은 정상적인데(틀린 비번 넣으면 alert)
로그인 후 화면이 변동없음.

**Comment by kieregh** [comment]
관련 이슈는 2.1.0 에서 수정되었으며 아래의 링크를 참조요청 드리며 클로징하겠습니다.
https://github.com/kimsQ/rb/issues/68
https://github.com/kimsQ/rb/commit/c5457217f146faf383fe7ff557163b0377441c57
