### ISSUE TITLE
modules/admin/action/a.admin_member_add.php 파일 61 라인....

### ISSUE THREAD

**Issue by kieregh** [kimsQ/rb#112]
회원정보 수정하는 부분 중 암호 수정하는 부분인데요...아래와 같은 오류가 있어 보입니다.
1) 암호 수정 안되는 문제...'pw...부분 ---> "pw ....로 시작해야 할듯...
2) 함수 인수값 오류 ..... $date['totime'] ---> 해당 회원 d_regis 값으로 변경 

아래와 같이 수정코드 제안합니다. 

현재 
<pre>
getDbUpdate($table['s_mbrid'],'pw='.getCrypt($pw,$date['totime']),'uid='.$uid);
</pre>

변경제안 
<pre>
$M=getDbData($table['s_mbrdata'],'memberuid='.$uid,'*');
getDbUpdate($table['s_mbrid'],"pw='".getCrypt($pw,$M['d_regis'])."'",'uid='.$uid);

</pre>

**Comment by kimsnova** [comment]
61라인부터 원본소스코드는 다음과 같습니다.

	$_M = getDbData($table['s_mbrdata'],'memberuid='.$uid,'d_regis');
	$newPw = getCrypt($pw,$_M['d_regis']);
	getDbUpdate($table['s_mbrid'],"pw='".$newPw."'",'uid='.$uid);
	getDbUpdate($table['s_mbrdata'],"email='$email',name='$name',nic='$nic',photo='$photo',tel2='$tel2'",'memberuid='.$uid);
	if ($my['uid'] == $uid)
	{
		$_SESSION['mbr_pw']  = $newPw;
	}
}
