### ISSUE TITLE
암호가 암호화되지 않고 저장되네요. 

### ISSUE THREAD

**Issue by gimapei** [kimsQ/rb#113]
Mysql테이블중에

rb2_s_mbrdata 에는 사용자 암호가  text로 저장되어 있습니다. 
rb2_s_mbrid 테이블에는 암호화 되어 있고요. 

어디든 암호화가 풀려있음 안될것 같습니다.

**Comment by kieregh** [comment]
사용자 로그인 암호는 s_mbrid 테이블에만 저장이 되며 암호화 방식은 아래 이슈내용을 참조하시기
바랍니다. 
https://github.com/kimsQ/rb/issues/58
