### ISSUE TITLE
레이아웃 이름에 '_' 포함된 경우, 레이아웃 디렉토리가 정상 처리되지 않는문제

### ISSUE THREAD

**Issue by BootstrapKR** [kimsQ/rb#114]
**[현상]**
1. Rb1.2 스타일로 레이아웃 이름을 my_layout 으로 결정
2. 압축파일 생성 (rb_layout_my_layout.zip)
3. Rb2에서 레이아웃 설치
4. 레이아웃이 my 디렉토리에 설치됨

**[원인]**

* /modules/market/action/a.add_layout.php
```
...
$nameinfo	= explode('_',str_replace('.zip','',$realname));
$plFolder	= $nameinfo[2];
...
```

**[수정제안]**

* /modules/market/action/a.add_layout.php
```
...
$nameinfo	= explode('_',str_replace('.zip','',$realname));
$plFolder	= $nameinfo[2];

// 이름에 '_' 포함된 레이아웃 디렉토리 처리
for($_i=3; $_i<count($nameinfo); $_i++) {
	$plFolder .= '_';
	$plFolder .= $nameinfo[$_i];
}
...
```

**[기타 의견]**

이 외에도 a.add_module.php 을 포함, 압축파일 설치 로직에서 동일한 코드를 발견할 수 있습니다.
의도된 사항이라면,  문서에 레이아웃, 모듈에 대한 네이밍 룰에대한 안내와 실제 프로그램에서 잘못된 이름 형식이라고 메시지박스를 뿌려주는게 좋을 것 같습니다.

```
$nameinfo	= explode('_',str_replace('.zip','',$realname));
$plFolder	= $nameinfo[2];

if( count($nameinfo)>3 ) getLink('', '', '설치파일 이름이 올바르지 않습니다.\n레이아웃 이름에 "_" 문자를 사용할 수 없습니다.', '');
```

개인적으로는 Rb1.2 처럼 '_' 문자 허용해 주는게 좋을것 같습니다.
혼란스럽거든요...^^

**Comment by kieregh** [comment]
2.1.0 릴리즈에서 아래와 같이 수정되었습니다.
https://github.com/kimsQ/rb/commit/59fa717e047b2e1fb9bfa9c3f2892f77d85433a9
