### ISSUE TITLE
다국어 처리관련 의견사항입니다.

### ISSUE THREAD

**Issue by maxdev-jh** [kimsQ/rb#115]
우선, 아래 사항은 순전히 개인적인 의견이고 또 Rb2 구조적인 이슈를 포함하니 참고만 해 주십시요.
그럼에도 불구하고 이슈를 제기하는 것은, 실제 글로벌 마켓에 런칭되기 전에 한번 더 검토하는 것이 장기적으로 도움이 될것 같다고 생각하기 때문입니다.

**1. 디폴트(기본) 언어에 대한 의견**

Common sense는 기본 언어는 사용자(관리자)가 설정한 언어이어야 한다고 봅니다.
이에 따라서, 그에 해당하는 언어파일(리소스)을 로딩 처리하면 그만입니다.

그런데, 모듈이나 레이아웃에 DEFAULT 폴더나 파일이 있고 이곳에 한글이 표기되어 있습니다.
개인적으로 이것이 어떤식으로 동작한다는 것인지 직관적으로 이해가 되지는 않습니다.

관리자가 설정한 언어 파일이 없는경우 사용되는 언어이다... 라는 의미로 해석은 됩니다만,
그러한 의미라면 설정값이 없을 때 사용되는 기본 언어코드를 static 하게 처리되는 것이 맞다고 보이구요, 해당하는 언어파일이 없다면 문자열 출력이 안되는 것이 맞다고 보입니다. (이런다면 명백히 해당 모듈 등의 오류이거나 구성상의 문제겠죠)

추가적으로, 언어파일 이름 english 처럼 길지 않고, en-us, ko-kr 등 단축형 언어코드였으면 좋겠네요.
영어도 미국식, 영국식이 있으니까 처음부터 고민되었으면 합니다.

**2. _LANG() 함수에 대한 의견**

이 부분의 주요 이슈는 코드 가독성 문제인데, 1번 항목의 해당 레이아웃, 모듈의 기본언어 처리와도 연관이 있습니다.

우선, 개발자나 사용자 할것없이 코드 가독성은 중요한 문제이며, 특히 프론트-앤드 단에서 보여지는 문자열을 기준으로 소스코드를 파악하기 시작합니다. 그런데, 현재는 인지하기 어려운 ID값만이 존재하므로 언어파일과 동시에 뒤적거리면서 찾아가야 하기 때문에 소스코드 분석이나 수정에 상당한 피로감을 야기시킵니다. 

그런데, 사실 대부분의 사용자에게 다국어 지원이 중요하지 않거나 불필요할 것입니다.
있어서 나쁠것은 없지만 이것때문에 두고두고 불편함을 야기한다면 제고할 가치는 충분하다고 봅니다.

따라서, 코어에서 다음과 같은 함수를 추가적으로 지원해 줄 것을 제안합니다.

```
function _L('모듈 식별자', '문자열 ID', '디폴트 문자열');
```

이 함수를 사용하게 되면 다음과 같이 가독성이 증가하는 효과가 있습니다.

기본함수 사용 시,

```
                    <a href="#" class="rb-modal-login" data-toggle="modal" data-target="#modal_window">
                        <?php echo _LANG('s3003','xlayout')?>
                    </a>
```

단축형 함수 적용 후,

```
                        <a href="#" class="rb-modal-login" data-toggle="modal" data-target="#modal_window">
                            <i class="glyphicon glyphicon-log-in"></i> <?php _L('layout', 'signin', '로그인')?>
                        </a>
```

실제적으로, 제가 만드는 레이아웃에 추가하여 별도로 사용하고 있는 함수이며 다음과 같이 코딩되어 있습니다. (_LANG() 함수 참고하여 약간 변형했을 뿐입니다.)

```
function _L($module, $kind, $default)
{
    echo ($GLOBALS['lang'][$module][$kind])? $GLOBALS['lang'][$module][$kind]: $default;
}
```

이 함수를 사용함으로써 저는 lang.DEFAULT.php 파일을 작성하지 않아도 되는 이득을 얻습니다.

또한, echo _LANG 을 모두 타이핑 하지 않아서 매우 편리합니다.

그리고, 문자열 아이디 값은 작성자 자유겠지만, 저같은 경우 의미있는 영문을 이용함으로써 차후에 영어 언어파일 변환에도 어느정도 부담을 덜게 되었습니다. (물론, 여유가 되면 동시에 영어파일도 작성하는게 좋기야 하지만요)

가장 큰 이득은 코드 가독성입니다.

물론, 한국 개발자가 만든거라 한국 사람에게만 유효하겠다 보실지 모릅니다.
하지만, 일본어 사용자라도 'signin' 정도는 이해할테니 보다 손쉽게 추측이 가능할 것입니다.
또한, 소스코드 자체가 UTF-8 기준이므로 한글이 깨져 보이지도 않으므로 보이기에 나쁠것도 없습니다. (각종 주석도 한글인데... 만약 진정한 글로벌 마켓을 고려한다면 개발자가 디폴트 문자열부터 주석까지 모두 영문으로 작성해야 된다고 봅니다.)

추가적으로, 1번 이슈에서 설정된 언어 파일이 없을 때 처리되는 그야말로 디폴트 값입니다.
만약, 일본 개발자가 개발한 모듈을 사용하는데 한국어 지원이 안된다면, 아무리 기본언어 설정을 한글로 해두어도 한글이 나오지 않고 일본어가 나오겠지요. 자연스러워 보이며 문자열이 안나오는 것보다는 좋을것 같습니다.

이걸보고, 누군가가 한글로 번역하여 언어 파일만 추가해 주면 한글도 정상적으로 출력 될 것입니다.

조건문을 하나 더 거침으로써 발생하는 런타임의 증가는 무시하겠습니다.
그런것이 두렵다면 다국어 생각하면 안되겠지요.

**3. name.txt 다국어 지원관련 문의**

name.txt에 한글로 "내 레이아웃" 이렇게 했을 때... Rb2 기본언어가 영어이면 어떻게 영어 이름으로 표기해 줄 수 있는가? 입니다. (모듈 포함)

자세히 뜯어보진 못했지만 방법을 모르겠네요. 그리고, 직관적으로 이해하기 쉬웠으면 좋겠으며 기본 레이아웃에서 그 방법이 제시가 되었으면 합니다.

일관성있게, _languages에 name.english.txt 하는것도 좋을 듯 하고...
그렇다면, _language 디렉토리는 언어별 서브디렉토리로 정리좀 되었으면 그것도 좋겠고요...^^;

이상 참고해 주세요.

**Comment by kieregh** [comment]
2.1.0 릴리즈에서 아래와 같이 요청하신 함수가 추가되었습니다.
https://github.com/kimsQ/rb/commit/c20915cb2f90d1bedb39fadb283676e2949da05f

3. name.txt 다국어 지원관련 
이 부분은 좀더 연구를 해봐야할텐데요...
우선 관리자 페이지만 다국어처리가 되는 것을 목표로 해야 할 것 같습니다.
