### ISSUE TITLE
layouts/MyLayout/_var/_var.config.php 에서 내 레이아웃 정보를 얻을 수 없는 문제

### ISSUE THREAD

**Issue by BootstrapKR** [kimsQ/rb#116]
$d['layout']['php']='_blank/default.php' 값이 설정되는 문제로, 레이아웃 설정 판넬에서 자신의 디렉토리 정보등을 얻을 수 없음으로 보다 다양한 레이아웃 옵션을 제공할 수 없게 됩니다.

예를 들어, 레이아웃 내에 테마를 내장하여 사용자에게 선택하도록 설정옵션을 제공하고자 할 때 등입니다.

오락가락 하는 원인은 알아낸듯 한데요... 
단일 사이트일 때에는 정상 동작하고, 서브 사이트를 생성하면 _blank 레이아웃이 들어갑니다.
(서브사이트 제거 후에는 단일 사이트여도 지속적으로 _blank 설정 됨)

좀더 정확하게, 
$m=site(단일 사이트 일 때) 이면 정상동작하고, $m=admin(서브사이트 있을 때) 이면 index.php의 아래 코드에 의해 _blank 레이아웃이 설정됩니다.

```
if ($m=='admin' || $iframe=='Y') $d['layout']['php'] = $_HM['layout'] = '_blank/default.php';
```

관리자 판넬에서는 사이트 > 사이트 페이지에 접근한 상황입니다.
서브사이트가 없을 때에는 m=null 이라 main.engine.php 에서 $g['sys_module'] 값으로 설정해 주는것 같은데요, 서브사이트가 있으면 m=admin이 됩니다.

왜 그래야 하는지까지는 잘 모르겠네요.
실제적으로 관리자 판넬의 메뉴 링크에는 m=admin 이므로, 항상 정보를 얻지 못해야 정상같은데...
단일 사이트 일때에만 m=null 이 들어와서 결국 m=site 로 설정되는것 같네요. 신기합니다.
개념적으로는 관리자 판넬은 판넬일 뿐, m=site 와 같이 동작하는 것이 정상적으로 보이구요...

어찌됬든, 이러한 사유로 인하여 보다 다양한 레이아웃 옵션 제공에 제약사항이 발생하게 됩니다.
수정이 가능하다면 최대한 빠른 시일내로 지원이 되면 좋을 것 같습니다.
이상 참고해 주십시요.

**Comment by kieregh** [comment]
2.1.0 에서 아래와 같이 수정되었습니다.
https://github.com/kimsQ/rb/commit/9477918ce8f1f9b6bd2b02d7d4f355513f82f94c
https://github.com/kimsQ/rb/commit/99b774c79390f5224fa3483ae1779f8b4aaf3b56
