### ISSUE TITLE
트리메뉴 펼치기 버그

### ISSUE THREAD

**Issue by taiji88** [kimsQ/rb#117]
트리메뉴에서 클릭한 메뉴의 uid의 앞자리가 같을때
첫번째 메뉴가 펼처지는 버그 입니다.
예를들어 menu를 생성하고 1차메뉴 uid가 1이라 가정.
여러개의 부메뉴를 만들고 1차메뉴를 새롭게 하나 생성한후 그 메뉴의 코드값이 11이라 하면
새로 생성한 메뉴 클릭시 첫번째 메뉴가 펼처지는 현상이 있음.
(트리 검사시 코드와 매칭하여 검사를 하는데 본 메뉴 uid의 길이만큼 자른것으로 검색하므로, 결과적으로는 같은 1이라는 결과가 나오기 때문에 그런것임)

/_core/function/sys.func.php (380라인)

$topen= $rcode==substr($code,0,strlen($rcode))?true:false;
=>
$t_arr = explode('/', $code);
$t1_arr = explode('/', $rcode);
$topen= in_array($t1_arr[count($t1_arr)-1], $t_arr)?true:false;

pull request에 올려야 하는데
지금 뭔가 꼬여서 일단 여기 올립니다.
정리되는대로 pull request에 올리겠습니다.

**Comment by kieregh** [comment]
2.1.0 에서 아래와 같이 수정되었습니다.
https://github.com/kimsQ/rb/commit/63a2482dbfe320c911d401f704d5e2f0490f4f0b
