### ISSUE TITLE
영어로 설치할 때 설명(lang.install.php)을 다듬었습니다.

### ISSUE THREAD

**Issue by sevenhopes** [kimsQ/rb#120]
직장에서 매일 영어로 생활하고 있습니다. 지난 번 How to install을 번역했는데, 아직 반영이 안 되었나 보군요.

제 번역에 대한 설명이 필요한 경우 ***로 표시하고 라인 맨 끝에 주석으로 달았습니다.
아직 github를 잘 몰라서 lang.install.php를 여기에 그냥 올립니다. 텍스트편집기로 복사해서 보셔야 좀 편할 것 같네요. 단순히 뜻만 새로 번역한 것이 아닌 설치과정을 따라하면서 어색한 부분까지 수정하여서, 외국인이 설치할 때 자연스럽게 느끼도록 신경 썼습니다.

<?php
$lang['install']['flag'] = 'en'; //en
$lang['install']['i001'] = 'KimsQ Rb Installation' //'Install KimsQ Rb'; //KimsQ Rb 설치
$lang['install']['i002'] = 'Select the version' //'Please select a package you want to install.'; //설치할 패키지를 선택해주세요. *** 사이트 패키지와 용어 혼동
$lang['install']['i003'] = 'Do not refresh this page. It will automatically move on to the next step after the downloading. The time of downloading depends on your network environment.' //'Please do not refresh because this automatically will move to next step after downloading. It may takes over several seconds in network condition.'; //다운로드 완료 후 자동으로 다음단계로 이동되니 새로고침 하지 마세요.<br class="hidden-xs">네트웍 상태에 따라 다운로드에 수초가 소요될수 있습니다.
$lang['install']['i004'] = 'Start Installation' //'Install Now'; //설치하기 *** 실제 설치는 모든 정보를 입력 후 이루어짐. 마지막 Next 버튼이 Install Now가 되어야 함.
$lang['install']['i005'] = 'You can also install KimsQ Rb by uploading its files directly.' //'You can also install Rb using direct upload.'; //또는 패키지 파일을 업로드해 주세요.
$lang['install']['i006'] = 'Browse a (zip) file' //'Browse file'; //파일 찾기 *** zip 파일만 허용하는 경우 괄호 해제
$lang['install']['i007'] = 'KimsQ Installer'; //킴스큐 인스톨러
$lang['install']['i008'] = 'Agreement'; //사용조건 동의
$lang['install']['i009'] = 'Set Database'; //데이터베이스
$lang['install']['i010'] = 'Create Admin' //'Regist User'; //사용자 등록 *** 사실상 일반 사용자가 아닌 관리자 계정이므로. Regist는 없는 단어.
$lang['install']['i011'] = 'Create Site'; //사이트 생성
$lang['install']['i012'] = 'License Agreement'; //사용조건 동의
$lang['install']['i013'] = 'Open Source Software License'; //오픈소스 소프트웨어 라이선스
$lang['install']['i014'] = 'I agree to the license above.' //'I agree with this license policy.'; //위의 라이선스 정책에 동의 합니다.
$lang['install']['i015'] = 'Database Information' //'Database settings'; //데이터베이스 설정 *** DB를 설정하는 게 아님, 설정된 DB의 정보를 입력하는 것
$lang['install']['i016'] = 'Basic Info' //'Default'; //기본정보
$lang['install']['i017'] = 'Advanced Options' 'Advanced'; //고급옵션
$lang['install']['i018'] = 'DBMS' //'DB kind'; //DB종류 <small>(type)</small>
$lang['install']['i019'] = 'DB name'; //DB명 <small>(name)</small>
$lang['install']['i020'] = 'Username'; //유저 <small>(username)</small>
$lang['install']['i021'] = 'Password'; //암호 <small>(password)</small>
$lang['install']['i022'] = 'Type your database information. Installation will be finished successfully only with the correct information.' //'Please input the Database(MySQL) infomation exactly. You can go to next step with correct infomation.'; //데이터베이스(MySQL) 정보를 정확히 입력해 주십시오. <br class="hidden-xs">입력된 정보가 정확해야만 정상적으로 설치가 진행됩니다. *** 입력을 아무렇게나 해도 사실 next step으로는 갈 수 있음. 마지막에 설치가 안 될 뿐. 키보드로 입력하라고 할 때는 input은 어색, type이 자연스러움.
$lang['install']['i023'] = 'DB Host'; //호스트 <small>(Host)</small>
$lang['install']['i024'] = 'Change this if your DB is running on the remote server' //'Change this if the DB is on remote server.'; //데이터베이스가 다른 서버에 있다면 이 설정을 바꾸십시오.
$lang['install']['i025'] = 'DB Port' //'DB port'; //포트 <small>(Port)</small>
$lang['install']['i026'] = 'Change this if the port of your DB server is different' //'Change this if the DB server port is not defalt.'; //DB서버의 포트가 기본 포트가 아닐 경우 변경하십시오.
$lang['install']['i027'] = 'Table Prefix' //'Table prefix'; //접두어 <small>(Prefix)</small>
$lang['install']['i028'] = 'Change this if you want to install more than one KimsQ Rb on your server' //'Change this if KimsQ has been installing on this server already.'; //단일 DB에 킴스큐 복수설치를 원하시면 변경해 주십시오.
$lang['install']['i029'] = 'DB Engine' //'DB engine'; //형식 <small>(Engine)</small>
$lang['install']['i030'] = 'MyISAM is the basic engine' //'MyISAM is default.'; //기본엔진은 MyISAM 입니다.
$lang['install']['i031'] = 'These options are needed only for the specific cases. Do not change if you do not know what to do, or ask your hosting provider' //'These options is needed for specific case. please do not change these or ask your hosting provider if you do not know what you have to do.'; //이 선택사항은 일부 경우에만 필요합니다.<br class="hidden-xs">무엇을 입력해야할지 모를경우 그대로 두거나 호스팅 제공자에게 문의하십시오.
$lang['install']['i032'] = 'User Registration'; //사용자 등록
$lang['install']['i033'] = 'Basic Info' //'Default'; //기본정보
$lang['install']['i034'] = 'Extra Info' //'Advanced'; //추가정보
$lang['install']['i035'] = 'Name'; //이름
$lang['install']['i036'] = 'Email'; //이메일
$lang['install']['i037'] = 'ID (Username)' //'ID'; //아이디
$lang['install']['i038'] = '4 to 12 lowercase letters or numbers' //'English lower case + number 4~12'; //영문소문자+숫자 4~12자 이내
$lang['install']['i039'] = 'Password'; //패스워드
$lang['install']['i040'] = 'Retype' //'Password again'; //패스워드 확인
$lang['install']['i041'] = 'Nickname'; //닉네임
$lang['install']['i042'] = 'Sex'; //성별
$lang['install']['i043'] = 'Male'; //남성
$lang['install']['i044'] = 'Female' //'Femail'; //여성 *** 워드로 열어서 맞춤법 검사 정도는...
$lang['install']['i045'] = 'Birthday'; //생년월일
$lang['install']['i046'] = 'Lunar'; //음력생일
$lang['install']['i047'] = 'Phone'; //연락처
$lang['install']['i048'] = 'Create an administrator account. You can add more detail in the profile page after installation.' //'A user as a super administrator will be added by these information. You can add your other information in your profile page after installing.'; //입력된 정보로 신규 회원등록이 이루어지며 최고관리자 권한이 부여됩니다. <br class="hidden-xs">관리자 부가정보는 설치 후 프로필페이지 추가로 등록할 수 있습니다.
$lang['install']['i049'] = 'Create a site' //'Site Creation'; //사이트 생성
$lang['install']['i050'] = 'Site Name' //'Site label'; //사이트명
$lang['install']['i051'] = 'Type the name of your first site' //'Please input name of this site.'; //이 사이트의 명칭을 입력해 주세요.
$lang['install']['i052'] = 'Site Code' //'Site code'; //사이트 코드
$lang['install']['i053'] = 'Site Code makes the site recognizable among multiple sites.' //'This is code for distinguishing this site among others.'; //이 사이트를 구분하기 위한 코드입니다. *** 설치 후 사이트는 하나인데 others라고 하기엔 어색함.
$lang['install']['i054'] = 'sitecode'; //사이트코드
$lang['install']['i055'] = 'Using Permalink'; //고유주소(Permalink) 사용
$lang['install']['i056'] = 'Check if you want to have shortened URLs. (PHP rewrite_mod necessarily loaded)' //'You can make URL shorter.(in rewrite_mod available case)'; //주소를 짧게 줄일 수 있습니다.(서버에서 rewrite_mod 허용시)
$lang['install']['i057'] = 'This is the last step. After installation, you can create a navigation bar and pages, or apply a site package to build your own website at once.' //'KimsQ will be installed after writing site name and clicking next button. After installing, create menus,pages or use site packages.'; //사이트명 입력 후 다음버튼을 클릭하면 킴스큐 설치가 진행됩니다.<br class="hidden-xs">설치가 완료된 후에는 메뉴와 페이지를 만들거나 사이트 패키지를 이용하세요.
$lang['install']['i058'] = 'Previous'; //이전
$lang['install']['i059'] = 'Next'; //다음 *** 마지막 Next 버튼은 Install Now가 되어야 함.
$lang['install']['i060'] = 'Install this version?' //'Are you sure this version to install?'; //정말로 선택하신 버젼을 설치하시겠습니까?
$lang['install']['i061'] = 'Connecting to KimsQ Rb server...' //'Downloading KimsQ Rb..'; //KimsQ Rb 다운로드중.. *** 실제 다운로드 메시지는 i062
$lang['install']['i062'] = 'Now downloading from the server...'; //서버에서 다운로드 받고 있습니다...
$lang['install']['i063'] = 'We\'re sorry. The selected version is not available now.' //'I am sorry, the package file you select is not available now.'; //죄송합니다. 선택하신 버젼은 아직 다운로드 받으실 수 없습니다.
$lang['install']['i064'] = 'We\'re sorry. The selected file is not KimsQ Rb.' //'I am sorry, it is not KimsQ package file.'; //죄송합니다. 킴스큐 패키지가 아닙니다.
$lang['install']['i065'] = 'You do not have proper permissions for the destination folder.\nTry again after changing the permission to 707' //'You have no permission to write at the install folder.\nTry again after changing the permission to 707'; //설치폴더의 쓰기권한이 없습니다.\n퍼미션을 707로 변경 후 다시 시도해 주세요.
$lang['install']['i066'] = 'Uploading KimsQ Rb...' //'Uploading KimsQ Rb..'; //KimsQ Rb 업로드중.. *** 말줄임표
$lang['install']['i067'] = 'Unzipping installation file on the server...' //'Unzipping package file on the server...'; //서버에서 패키지 압축을 풀고 있습니다... *** 사이트 패키지와 혼동
$lang['install']['i068'] = 'DB Host is required.' //'The DB host is required and cannot be empty.'; //DB호스트를 입력해 주세요.
$lang['install']['i069'] = 'DB Name is required.' //'The DB name is required and cannot be empty.'; //DB명을 입력해 주세요.
$lang['install']['i070'] = 'DB Username is required.' //'The DB user is required and cannot be empty.'; //DB사용자를 입력해 주세요.
$lang['install']['i071'] = 'DB Password is required.' //'The password is required and cannot be empty.'; //DB 패스워드를 입력해 주세요.
$lang['install']['i072'] = 'DB Port number is required' 'The DB Port number is required and cannot be empty.'; //DB 포트번호를 입력해 주세요.
$lang['install']['i073'] = 'Table Prefix is required and cannot be empty' //'The Table prefix is required and cannot be empty.'; //DB 접두어를 정확히 입력해 주세요.
$lang['install']['i074'] = 'Administrator account\'s name is required.' //'The Name is required and cannot be empty.'; //이름을 입력해 주세요.
$lang['install']['i075'] = 'Administrator\'s email address is required.' //'The Email address is required and cannot be empty.'; //이메일주소를 정확히 입력해 주세요.
$lang['install']['i076'] = 'Administrator\'s id is required.' //'The ID is required and cannot be empty.'; //아이디를 정확히 입력해 주세요.
$lang['install']['i077'] = 'Administrator\'s password is required.' //'The password is required and cannot be empty.'; //패스워드를 입력해 주세요.
$lang['install']['i078'] = 'Fill the both of two blanks for Administrator\'s password.' //'Please input the password again.'; //패스워드를 다시한번 입력해 주세요. *** 두번째 패스워드 칸이 비었을 경우, 그냥 다시 입력하라는 설명은 너무 모호함
$lang['install']['i079'] = 'The both passwords are not identical.' //'Both passwords are not same.'; //패스워드가 일치하지 않습니다.
$lang['install']['i080'] = 'Installing KimsQ Rb now. Please wait a second.' //'Now installing. Please wait a seconds.'; //설치중입니다. 잠시만 기다려 주세요.
$lang['install']['i081'] = 'Type Site Name, please.' //'Please input the site name.'; //사이트명을 입력해 주세요.
$lang['install']['i082'] = 'Type Site Code, please.' //'Please input the site code exactly.'; //사이트 코드를 정확히 입력해 주세요.
$lang['install']['i083'] = 'Start the installation with the typed information?' //'Do you want to go next step really?'; //정말로 설치하시겠습니까?
?>

**Comment by sevenhopes** [comment]
특히 킴스큐 설치 파일을 '패키지 파일'이라 부르는 것은, '사이트 패키지'와 네이밍이 겹쳐 혼동이 야기될 수 있으므로 둘 중 한 용어를 버리시는 것을 제안합니다. 사이트 패키지는 쉽게 바꿀 수 없으므로, 패키지 파일을 배포용 파일(distribution file), 이나 다른 이름으로 바꿀 것을 건의해 봅니다.

**Comment by kieregh** [comment]
번역작업 감사드립니다. 

2.1.0 버전에서 제안해주신 번역내용 최대한 반영하여 아래와 같이 수정되었습니다.
https://github.com/kimsQ/rb2-installer/commit/39dd7d9e8b56ec1651ebe8efbe0953053cacd6a4
