### ISSUE TITLE
관리자 모드에서의 모듈메뉴 탭

### ISSUE THREAD

**Issue by maxdev-jh** [kimsQ/rb#122]
모듈의 메뉴가  특정 개수 이상 일 때, [더 보기]로 줄여서 보여지지 않는 문제가 있습니다.
- 모니터 해상도: 1600x900

아래, 스크린샷 참고 바랍니다.
![image](https://cloud.githubusercontent.com/assets/8796513/6618179/128da9d0-c904-11e4-9bdb-c6baa1d3ae6d.png)

**Comment by newhwa** [comment]
[더보기] 표시되지 않아야 할 경우에 표시되는 경우도 있습니다.즉 더보기 클릭하면 드롭다운 메뉴가 비어있습니다. bbs모듈 설치하시면 이슈 확인이 가능합니다.

**Comment by kabkee** [comment]
개인적으로 모듈을 만들어 사용하는 과정에서 아래와 같은 문제가 발생하여 함께 공유합니다.
1) 5개의 탭이 있는데, 유독 3번째 탭에서 더보기가 없고, 오른쪽 끝 border가 없이 나옵니다.
<img width="533" alt="2015-07-30 10 40 51" src="https://cloud.githubusercontent.com/assets/3394175/8974025/ce318fce-36a7-11e5-89be-55f751424f4b.png">
2) 3번째 탭을 제외하고 모든 탭에서 불필요한 "더보기"탭이 추가 됩니다.
<img width="515" alt="2015-07-30 10 41 19" src="https://cloud.githubusercontent.com/assets/3394175/8974024/ce2f3ac6-36a7-11e5-8507-af1fcdf5aba6.png">
