### ISSUE TITLE
시스템 _blank 레이아웃 추가 고려사항

### ISSUE THREAD

**Issue by BootstrapKR** [kimsQ/rb#123]
2.0에서도 ...&iframe=Y 파라미터와 함께 페이지 호출 시, 시스템의 _blank 레이아웃이 호출됩니다.

그런데, _blank 레이아웃에는 실제 컨텐츠 외에 `<html><head></head>...` 부분 및 Bootstrap 관련 CSS 까지 모두 들어가게 되므로 다음과 같은 문제가 발생합니다.

* 특정 레이아웃이나 모듈의 팝업 또는 iframe 페이지(이하 서브페이지)에서 Bootstrap CSS로 인해 디자인이 원하지 않는 방향으로 표현될 수 있음
* Bootstrap을 사용하지 않는 레이아웃 또는 모듈의 서브페이지에서 Bootstrap CSS로 인해 디자인이 깨짐

이는, 레이아웃에서 `<head>` 태그를 처리하도록 구조가 변경됨에 따른 문제점일 것인데요... 꽤 고민해볼 사항입니다.

각 모듈에서 Bootstrap을 사용한다면, 현재 설정된 레이아웃에서 커스터마이징 된 Bootstrap CSS가 필요할 수 있습니다. 그래야, 레이아웃에서 커스텀 한 Bootstrap 디자인이 일관성 있게 모듈에도 적용이 가능합니다. (예를 들어, 레이아웃에서 btn을 rounded 없도록 변경한 경우 등)

그 다음, 해당 모듈에서 정의한 CSS가 적용되어야 할 것입니다. 
(모듈에서 필요에 따라 정의한 값을 우선순위를 두어 적용)

따라서, _blank 레이아웃은 사용자가 설정한 레이아웃 내에 위치하는 것이 타당해 보입니다.
보다 정교하게는, layout을 선택할 수 있도록 해주는 방법이 있을것 같네요.

예를 들어...

* ...&iframe=Y 호출 시, 현재처럼 시스템의 _blank 레이아웃 사용
* ...&iframe=Y&scope=layout&layout=_blank 호출 시, 현재 사용자가 설정한 레이아웃의 _blank 서브 레이아웃 사용
* ...&iframe=Y&scope=module&layout=_blank 호출 시, 모듈 내에서 정의한 _blank 레이아웃 사용
* 단, 모듈 또는 레이아웃의 _blank 미 존재 시, 시스템의 _blank 레이아웃 사용

뭐, 이런식으로 구성하는 방법이 있을 듯 합니다.
저 역시 복잡해 지는것을 싫어하지만... 현재 상태로는 분명 구성에 제약사항이 크게 느껴집니다.

위에서, &layout=_blank 부분은 생략 가능하겠으나... _null 레이아웃 또는 개발자 정의 레이아웃 등 추가 고려사항 있을 수 있어서 적어보았습니다. 그리고, 모듈의 레이아웃은 오바인 것은 알고 있고요..^^;

최소한, ...&iframe=Y 과 ...&iframe=Y&scope=layout 정도는 지원되었으면 합니다.
아니면, 현재처럼 ...&iframe=Y 만 지원하되 사용자 레이아웃 내의 _blank 서브레이아웃에 우선순위라도 주었으면 좋겠네요.

이 문제는 특히 Bootstrap을 사용치 않는 레이아웃/모듈에서 불거질 것입니다.
(Bootstrap 레이아웃 + Bootstrap 모듈이더라도 문제가 있는 것은 마찬가지 입니다만...)

따라서, 차기버전 업데이트 전에 반드시 고민되었으면 합니다.
이상 참고해 주세요.

:boom: 이 이슈는 https://github.com/kimsQ/rb/issues/101 과 같이 고민할 필요가 있어 보입니다.

**Comment by kieregh** [comment]
네...Rb2.0 의 구조적인 결함을 종합적으로 분석해주신 것 같습니다.

2.1.0 릴리즈 버전에서 제기하신 이슈 해결을 위해서 아래와 같이 수정되었습니다.   
https://github.com/kimsQ/rb/commit/9477918ce8f1f9b6bd2b02d7d4f355513f82f94c
https://github.com/kimsQ/rb/commit/008ce9152920741f15d7e00843b9efdc36a9cf78
https://github.com/kimsQ/rb/commit/ee35afaeab736cdf272cb6aca07d64c2b0ca4504
https://github.com/kimsQ/rb/commit/2f4604a9c9499b4087cedfbcdd77c004492b5a05
