### ISSUE TITLE
마켓 페이지로딩 안됨

### ISSUE THREAD

**Issue by kabkee** [kimsQ/rb#133]
마켓 setting에 로그인 정보를 넣고,
마켓을 클릭하면,
로그인 정보를 넣고 안넣고를 떠나 마켓 페이지 로딩이 안됩니다.

**Comment by gitaeks** [comment]
Rb2 내부의 마켓의 경우  Rb2 전용마켓이 연결되어야 하는데요. Rb2 전용마켓은 개발중에 있는 관계로 연결이 안되고 있는 상태 입니다.  혼선이 없도록 파킹페이지를 연결하도록 하겠습니다.
