### ISSUE TITLE
Bootstrap class 사용 alert종류 관련

### ISSUE THREAD

**Issue by kabkee** [kimsQ/rb#134]
정보를 보여주기 위한 내용에 대한 class가 alert-success 일괄 적용 사례발견.
대안) 해당 의도와 맞는 css 클래스 사용을 한다.

msg.
개발자님께서 특정이유로 일부러 success로 일괄적용하신 의도가 있으신지 모르겠으나, 적어봅니다.

**Comment by gitaeks** [comment]
Rb2 관리자에서의 심플함을 유지하기 위해 칼라는 정의된 컬러 범위내에서만 사용하고 칼라 수도 제한적으로 사용하였습니다.
bootstrap에서 정의 된 [컬러셋] (http://getbootstrap.com/css/)을 사용했습니다.

* default
* primary
* success
* info
* warning
* danger

### 페이지내에 주된 액션요소의 경우
페이지내에 주된 액션요소에 주된(primary)  칼라의 경우 부여
![image](https://cloud.githubusercontent.com/assets/5070245/7221880/9035be4c-e739-11e4-92e0-1892db592096.png)

### 아이템의 활성(active)의 상태의 경우
주된(primary)  칼라의 경우 부여
![image](https://cloud.githubusercontent.com/assets/5070245/7221880/9035be4c-e739-11e4-92e0-1892db592096.png)


### 삭제와 관련된 요소의 경우
삭제와 관련되어 주의가 필요한 요소에는 위험(danger) 클래스를 적용했습니다.
![image](https://cloud.githubusercontent.com/assets/5070245/7221882/a1c9856c-e739-11e4-82c6-2297eb23354b.png)

success 클래스는 거의 사용이 안되어 있는 것으로 아는데요.
primary는 위와 같은 원칙을 가지고 사용되었습니다.

좋은 하루 되세요.


 ,

**Comment by kabkee** [comment]
적정답변으로 이슈 종료합니다.
