### ISSUE TITLE
회원가입 및 로그인시 입력폼 유효성관련 제안

### ISSUE THREAD

**Issue by taiji88** [kimsQ/rb#138]
현재 2.x의 경우 기본 탑재된 회원가입 모듈이 없기에
회원과 관련한 각종 입력폼에 대한 유효성 검증을 할수가 없습니다.
아래는 제가 제안드리는 유효성 입니다.
1. 아이디: 관리자 로그인시 유효성 검증을 합니다.
   - 알파벳, 숫자, underscore(_), dot(.)만 가능. 나머지 불가능. (현재의 검증방법)
   - 4byte 이상
   - 12byte 이하
2. 비밀번호: 1.x버전의 암호 유효성이 너무 단순함.
   - 8byte 이상
   - 30byte 이하
   - 필수요소: 특수문자, 숫자 (협의가능)
3. 이메일: 현재 관리자 > 사용자 > 관리자 추가시 유효성을 그대로 가저감.
4. 닉네임
   - 1byte 이상
   - 20byte 이하

**Comment by kabkee** [comment]
죄송한데. 질문드겠습니다. 가입버튼이 없는것이 아직 개발이 안되어 그런게 맞는건지요. 내용상으로는 맞는듯 한데. 5월1일자로 현재까지 없는게 맞는건지 문의드립니다.
