### ISSUE TITLE
고유주소관련 오류대안 문의

### ISSUE THREAD

**Issue by kabkee** [kimsQ/rb#139]
기존의 짧은주소인 고유주소(Permalink)로 인한 오류가 발견되었습니다.
BSKRBBS(게시판모듈)을 사용 도중에 BBSID와 게시판코드의 고유주소 생성문제에서 생기는 오류인듯 합니다.
ex) r=home&c=Albumsmyalbums$mod=write 이 /home/c/Albums/write 으로 생성됩니다.

질문1) 고유주소 생성관련하여 어디를 확인하면 가장 빠를까요?

**Comment by gitaeks** [comment]
고유주소(Permalink) 를 처리하는 htaccess 파일에 문제가 확인됐습니다. 
https://github.com/kimsQ/rb/pull/141 를 참고해 주세요.

말씀하신 @BootstrapKR 님의 BSKRBBS(게시판모듈)은 별도의 m=bskrbbs 모듈아이디를 사용하는 만큼, 모듈 설치과정에서 htaccess 파일에 코드를 추가 업데이트 처리해야 할 것 같습니다.

**Comment by kabkee** [comment]
감사합니다 :+1: 
:smile:  이슈 닫습니다~
