### ISSUE TITLE
개발 & 개선 참여관련

### ISSUE THREAD

**Issue by kabkee** [kimsQ/rb#143]
개발 및 개선관련하여 참여하게 된다면. 고려사항이나 기본적인 규칙이 있는지 궁금합니다. 
풀리퀘스트를 올리면 누가 담당하고 처리하는지. 어떤 절차에서 거절이나 수긍되는지 현재까지의 일반화된 업무 처리를 간략하게 공유해주시면 감사하겠습니다.
관련하여. 위키나. 문서를 함께 공유하여 함께 개선한다면 더욱 좋을것 같습니다.

**Comment by gitaeks** [comment]
@kabkee 님, 적극적인 참여 감사드립니다. 제안해주신 대로 저장소 위키에 관련 가이드를 등록해 놓았습니다.  아래의 문서를 참고해주세요. 추가적인 요청이나 질문사항에 대해서 의견 달아주시면 검토하겠습니다. 
* [킴스큐 오픈소스 프로젝트 운영 지침](https://github.com/kimsQ/rb/wiki)

**Comment by kabkee** [comment]
자세하고 정돈된 답변 감사히 잘 읽어보았습니다 :+1:
