### ISSUE TITLE
모듈 설치 없이 작동 합니다.

### ISSUE THREAD

**Issue by ghost** [kimsQ/rb#151]
관리자에서 모듈 업로드가 아닌
FTP에서 모듈 업로드후 관련 URL 넣었을 경우 인식합니다.
그렇다고 FTP에서 업로드후 관라자에서 설치 한것도 아니에요.

**Comment by gitaeks** [comment]
말씀하신 사항이 이해가 되지 않습니다. 보충설명이 필요할 것 같습니다. 좀더 디테일한 상황 재현이 필요할 것 같습니다.
