### ISSUE TITLE
포토셋에 카테고리 이미지 카운터 오류 / 휴지통에 버린 이미지 갯수까지 포함됩니다.

### ISSUE THREAD

**Issue by hancoma** [kimsQ/rb#152]
포토셋 카테고리 이미지의 갯수가 휴지통에 버린 이미지 갯수까지 포함되어 있습니다.
카테고리 이미지 갯수가 4개 이고 이미지를 삭제한게 2개 있으면 6개로 나옵니다.
수정해주세요. 감사합니다.

**Comment by gitaeks** [comment]
네, 버그 확인했습니다. 제보 감사합니다.

![image](https://cloud.githubusercontent.com/assets/5070245/7877451/c1f25d90-0616-11e5-9c53-8a76c7be253b.png)
