### ISSUE TITLE
My homepage 가 나오는 이유가 뭔가요?

### ISSUE THREAD

**Issue by jsk005** [kimsQ/rb#153]
Layout 사이트 제목을 변경해서 첫페이지에는 변경된 레이아웃의 이름이 나오는데
게시판으로 연결되면 상단에 My homepage 라는 글씨가 보이니다.
설치한 게시판은 BSKR게시판 입니다.

**Comment by gitaeks** [comment]
혹시 레이아웃이 default 인가요 ?  default1 인가요?  URL을 공유해 주시면 확인해 보겠습니다.

**Comment by jsk005** [comment]
관리자모드에서 layout 에서 기본레이아웃/모바일레이아웃을 선택하면 무한루프에 빠지는 증상이 있어 보입니다.
테스트 환경 : 윈도우7, Firefox 브라우저
레이아웃명 : default-BS layout, default_BSKR default
두개만 눌러봤습니다.
![layout_select_bug-01](https://cloud.githubusercontent.com/assets/12641754/9295591/c41512b8-44ad-11e5-987f-4fe346a808a3.png)
