### ISSUE TITLE
member-develop, rb_module_bbs 설치시 에러 

### ISSUE THREAD

**Issue by godotpak** [kimsQ/rb#154]
kimsq live 서버에서 2.0을 정상적으로 설치하고...위 두 모듈을 설치하였습니다.

정상적으로 설치는 된거 같은데...아래와 같은 에러가 계속 발생합니다.

Warning: include(./modules/member-develop/admin.php) [function.include]: failed to open stream: No such file or directory in /home/godot/www/modules/admin/theme/default/front.php on line 138

Warning: include() [function.include]: Failed opening './modules/member-develop/admin.php' for inclusion (include_path='.:/usr/local/php/lib/php') in /home/godot/www/modules/admin/theme/default/front.php on line 138

**Comment by kieregh** [comment]
안녕하세요. 케르입니다.

member-develop 는 Rb 에서 사용하는 모듈 패키지명이 아닙니다. 
github 에서 zip 으로 다운받을 때의 이름입니다. 이 것을 아래와 같이 이름을 수정해서
설치해주세요. 
rb_module_member.zip  

위 압축파일을 풀었을 때 바로 member 폴더 및 파일들이 나와야 합니다. 

답변이 늦었네요...
