### ISSUE TITLE
기타자료(etc) 등록시 에러

### ISSUE THREAD

**Issue by taiji88** [kimsQ/rb#159]
1.2.x에서는
기타자료 (rb_etc_모듈명.zip) 만들고 사이트에 등록할때
신규 모듈이 포함되어있고, 모듈 안 _setting에 DB가 추가되어 있을경우
나머지 위젯등을 세팅한후 다음 step에서 모듈설치를 눌러 모듈추가를 했었는데

2.0에서는 모듈 세팅과정이 없어 디렉토리에 복사만 되고
DB세팅이나 rb_s_module테이블에 모듈기록이 되지 않습니다.

최대한 빨리 패치가 되어야 할듯 합니다.

**Comment by gitaeks** [comment]
기타자료(etc) 의 경우 DB,추가 작업이 수행될 수 없이 파일만을 추가하는 속성을 가지고 있습니다. 그렇기 때문에  모듈,스위치,플러그인은 기타자료에 포함시켜서는 안됩니다.  
사이트패키지로 패키징하면 모듈,스위치,플러그인에 대해서도 자동설치가 됩니다

[개발자메뉴얼- 기타자료 만들기](http://docs.kimsq.com/rb2/docs/c/Dev/Extension/Others#myothers)
