### ISSUE TITLE
위젯캐쉬 미사용 관련

### ISSUE THREAD

**Issue by kabkee** [kimsQ/rb#161]
안녕하세요?
매번 캐쉬가 남아 재생성을 눌러줘야하는데요.
위젯캐쉬를 아예 미사용 상태로 변경할 수는 없는건가요?

![image](https://cloud.githubusercontent.com/assets/3394175/8665706/ef863c98-2a21-11e5-9fac-4d4ef7363d73.png)

**Comment by kieregh** [comment]
관리자 모드 > 시스템 도구  >  CSS/JS 캐시  항목에서 '브라우져 설정을 따름' 으로 선택해보시기 바랍니다.  이렇게 하면...$g[wcache] 값이 빈값으로 처리가 됩니다. 

참고로, 위젯케시설정은 아래 파일에서 설정됩니다.
_core/engine/widget.engine.php 26, 27 라인....
위 부분에서 $g['wcache'] 를 주석처리하면 확실한 방법이겠으나 가능한 관리자
페이지에서 설정으로 컨트롤하시는 것을 권장합니다.

감사합니다.

**Comment by kabkee** [comment]
확인되었습니다. 감사합니다.
