### ISSUE TITLE
_blank/default 레이아웃에 cssjs엔진 포함시키지 않은거 특수한 이유가 있는건가요?

### ISSUE THREAD

**Issue by newhwa** [kimsQ/rb#162]
이슈라고 확정은 못하지만 _blank/default 레이아웃에 cssjs엔진 포함시키지 않은거 특수한 이유가 있는건가요?

문제점:
개발한 모듈에 이 레이아웃(_blank)을 지정시키면 해당 모듈 폴더아래 있는 css/javascrip파일이 자동으로 인클루드 되지 않습니다.

**Comment by kieregh** [comment]
네..안녕하세요...

우선..._blank 레이아웃의 용도에 대해 말씀드리겠습니다.
이 레이아웃은 1.2 / 2.0 동일하게 2 가지의 경우에 사용됩니다.
1) $m=='admin' 즉, 관리자 모드인 경우 사용
2) iframe=Y 파라미터가 있는 경우 사용 

위 2 가지 경우 중 2) iframe=Y 의 경우는 이렇게 파라미터를 추가해서
윈도우창을 새롭게 띄워서 백단에서 데이타 처리를 하고 기존 레이아웃에 
영향을 받지 않고 내용을 보여주고자 하는 의도입니다.
(2.0 에서는 자체 모달 스크립트 함수를 제공함으로서 새로운 윈도우창 사용을 지양합니다.)

요컨대, _blank 레이아웃의 용도는 이미 정해져 있다고 할 수 있습니다.  
또한, css/js 엔진 코드는 1.2 에서는 index.php 구조상 그냥 모든 레이아웃에 포함되었지만
2.0 에서는 <html></html> 태그 부분이 레이아웃 쪽으로 이관되면서 <head></head> 쪽에
대한 옵션이 그만큼 확대되었다가 볼 수 있습니다. 그런 의미에서 _blank 레이아웃의 
<head></head> 쪽에 궂이 css/js 엔진이 필요한가에 대한 고민이 있었던 것 같습니다. 
적어도 2.0 에서는 _blank 레이아웃에서는 css/js 엔진이 필요 없다고 생각합니다. 이유는....
관리자 모드에서는 당연히 의미가 없구요...iframe=Y 같은 파라미터를 이용해서 새윈도우창을
띄우는 상황을 만들지 않기 위해 모달 스크립트를 사용하기 때문입니다.  

즉, 다시 본 이슈로 돌아와서...제가 궁금한 것은 어떤 의도로 _blank 레이아웃을 사용하셨는지에
대한 부분입니다.  예를 들어, _blank 레이아웃의 특징 중 하나는 top 부분과 bottom  부분에 html 이 
없기 때문에 컨텐츠 부분만 보여주고자 할 때 이 레이아웃이 의미가 있다고 생각하는데요...

결론적으로.....위에서 말씀드린 의도이면서...css/js 엔진이 필요한 상황이라면....
_blank 레이아웃를 복사하셔서 새로운 레이아웃을 추가하신 후 여기에 css/js 엔진 부분을
추가하셔서 사용하시면 될 것 같습니다.

도움이 되었는지 모르겠습니다.

**Comment by newhwa** [comment]
상세한 답변 감사드립니다.
제가 1.2.2에서 사용하던 소셜베이스 모듈(spack)을 rb 2.0으로 마이레이션 하던중에 모듈폴더아래 테마의 css가 적용되지 않아서 소스 뜯어보던중에 이 차이점을 발견하게 되었습니다. 아무튼 말씀하신대로 복사해서 다른 레이아웃 하나 만들내어서 문제는 해결되었습니다.
상세한 답변 다시 감사드립니다.
