### ISSUE TITLE
 preg_replace() PHP 5.4부터 deprecate 되네요.

### ISSUE THREAD

**Issue by livesam** [kimsQ/rb#163]
/core/function/lib/getContet.lib.php 파일 30라인에서 사용되어 에러메시지를 출력하는데 PHP 상위버전을 점점 더 많이 사용할 것이라는 전제하에 preg_replace_callback() 으로 변경하는 것이 좋겠습니다.

**Comment by kieregh** [comment]
안녕하세요. 

관심 가져주셔서 감사합니다.

아래 페이지를 보면...
http://php.net/manual/en/migration55.deprecated.php

해당...preg_replace() 함수는 5.5 부터 deprecate 된다고 나오는데요...
현재 사용하시는 사이트 어떤 페이지에서 본 이슈 관련한 dprecage 안내 문구가 
출력이 되었는지 알려주셨으면 합니다.  참고로, 사용하시는 php 버전도 좀 
알려주시기 바랍니다.

그럼...수고하세요...

**Comment by livesam** [comment]
php 5.5 부터 deprecate가 맞군요.
제 php는 5.6 이었습니다.

**Comment by gitaeks** [comment]
`preg_replace()` 함수가 사용되는 내역 입니다.
https://github.com/kimsQ/rb/search?utf8=%E2%9C%93&q=preg_replace%28%29

**Comment by djacks6278** [comment]
예전이지만 지금도 사용하기에 픽스를 올립니다.


		$str = preg_replace_callback('/<(.*?)>/i',
		function ($match) {
			return '<'.preg_replace(array('/javascript:[^\"\']*/i', '/('."implode('|', $onAttributes)".')[ \\t\\n]*=/i' , '/\s+/'), array('', '', ' '), stripslashes($match[1])).'>' ;
		}, $str);
