### ISSUE TITLE
댓글을 펼치면...계속 로딩중입니다. (현 KimsQ사이트도 동일)

### ISSUE THREAD

**Issue by gitaeks** [kimsQ/rb#164]
본 이슈는 [킴스온](http://www.kimsq.co.kr/profile/m000137)님이 제시한 이슈를 옮겼습니다.
http://www.kimsq.co.kr/?c=qna&p=2&uid=15825

댓글을 펼치면...계속 로딩중입니다. (현 KimsQ사이트도 동일)

Q/A 게시판 등에서 댓글이 있는 경우, 펼치면..
브라우저 타이틀영역에 계속 로딩중으로 됩니다.

킴스큐도 마찬가지고...
저희 사이트도 마찬가지네요..

댓글에서 계속 뭘 로딩하는 걸까요? (크롬브라우저에서 나타남)

![image](https://cloud.githubusercontent.com/assets/5070245/8896728/422505f6-3440-11e5-8b96-af085519c852.png)
참고) 위 킴스큐 브라우저 타이틀 좌측에 로딩중 이미지..

**Comment by kieregh** [comment]
안녕하세요. 케르입니다.

제 나름대로의 조사를 통해 얻은 결론은 아래와 같습니다. 

1. 문제의 원인으로 지목된 코드 분석 및 용도
    
 1) 문제의 원인으로 언급된 아래의 코드가 본 이슈의 원인인 것은 맞습니다.  
    EditForm.document.write(getId('setCssCode').innerHTML.replace(/&lt;/g,'<').replace(/&gt;/g,'>'));  

 2) 단지, 위 코드에서 원인으로 지목된  &lt; 를 < 로 변환하는 과정은 문제가 없는 것으로 
     보입니다.
 3) 이 코드의 용도는 댓글 박스 내부의 style 을 지정하기 위한 것으로 실제 해당 iframe 내부 
     <head></head> 안에 style 이 지정되어 있습니다. 
      따라서, 이 코드가 필요없다고 할 수는 없다고 생각합니다. 
  3) 테스트 해보시면 아시겠지만, 이 코드를 삭제했을 경우 댓글 박스에 글을 쓰면 폰트나 라인
      간격 등이 투박하게 출력이 됩니다. 

 2. 그렇다면 무엇이 문제인가? 

     위에서 말씀드린 대로 문제의 원인은 아래 코드가 제공합니다. 
     EditForm.document.write(getId('setCssCode').innerHTML.replace(/&lt;/g,'<').replace(/&gt;/g,'>'));

     그러나 진짜 원인은... getId('setCssCode').innerHTML.replace(/&lt;/g,'<').replace(/&gt;/g,'>')
     가 아니라.....document.write() 메소드 사용방법상의 오류로 보여집니다. 

      즉, document.write() 메소드를 사용한 이후에는 반드시 document.close() 메소드를 해줘야
      한다는 것입니다. 

      실제로...위 코드 아래에...아래의 한 줄 추가해주면 무한로딩 현상은 사라집니다.
      EditForm.document.close();


3. 왜 크롬에서만 그런가? 

    이 부분에 대한 힌트는 아래 글을 참조해주시기 바랍니다. 
    http://stackoverflow.com/questions/22842749/chrome-javascript-and-frames-not-working
    
up vote
0
down vote
accepted
In Chrome (i)frames are treated as cross-domain windows when running local pages (i.e. with file protocol). (Why?). Passing --allow-file-access-from-files switch at start-up should tackle the problem (credits @Justin).

Some observations of your code

framesets and frames are obsoleted in HTML5, if you really need external windows, use iframes instead.
Attribute values should be always wrapped in quotes. Unwrapped attributes are working now, but they might not work in the future. Also values containing spaces will break the markup.
A simple reference to (i)frame's window object is window.frames['frame_name'], you don't need complex window.open()
document.open() is not needed, document.write(ln)() opens the document automatically
After document.write(ln)() you have to close the document with document.close() to stop browser loading

4.  왜 최근에 이 문제가 이슈가 되었는가? 

   이 부분에 대해서는 아래의 2 가지 경우로 추측합니다. 

   1) 킴스큐 커뮤니티가 발견을 이제서 한 것이다.
   2) 크롬의 업그레이드가 진행되면서 iframe 에 대한 룰이 엄격해졌다.(보안 이슈)


기타 추가로 참고할만한 링크는 아래와 같습니다. 
http://stackoverflow.com/questions/27854494/javascript-document-open-and-document-close-is-necessary

http://stackoverflow.com/questions/7114798/why-does-document-write-always-cause-the-browsers-tab-to-show-the-loading-i

이상입니다.
