### ISSUE TITLE
php 5.5 에서 mktime() 함수 관련 에러 메세지 출력됩니다. - 1.2 /2.0 공통 

### ISSUE THREAD

**Issue by kieregh** [kimsQ/rb#181]
## php 5.5 환경에서 로그인을 하고 나면 아래와 같은 에러메세지가 출력됩니다.

Strict Standards: mktime(): You should be using the time() function instead in ....
## 아래의 페이지에 관련하여 안내가 되고 있습니다.

http://php.net/mktime 
---- 원문 -------
Note:
As of PHP 5.1, when called with no arguments, mktime() throws an E_STRICT notice: use the time() function instead.

---- 번역 ----------
주의 : 
PHP5.1이상버전에서는 인자가 없이 mktime() 함수를 호출하는경우는 E_STRICT notice 출력함.
time() 함수로 대체 사용하세요.
## 요컨대, PHP 5.1 이상에서는 mktime() 함수는 인자가 없이는 사용하면 안되며 대신 time() 함수를 사용해야 합니다.

참고로, 로그인시 그 동안 발견되지 않은 이유를 유추하건데....로그인 후 바로 redirect 되기 때문에
보이지 않았던 것으로 생각됩니다.  redirect 시간을 늘리면 위 에러 메세지가 redirect 과정서 잠깐 
노출되는 것을 인지할 수 있습니다. . 

이상입니다.

**Comment by gitaeks** [comment]
아래는 Rb에서 `mktime()` 가 사용되는 내역 입니다.
https://github.com/kimsQ/rb/search?utf8=%E2%9C%93&q=mktime%28%29
