### ISSUE TITLE
Layout - site title 에서 이미지 타이틀이 가끔 사라지는 현상

### ISSUE THREAD

**Issue by hulkzone** [kimsQ/rb#20]
일단 진도가 여기까지 나가도 되는건지 잘 모르겠는데요... ^^
![20140915_020625](https://cloud.githubusercontent.com/assets/8669920/4264725/8a193646-3c31-11e4-844b-c3544ea7c5ce.jpg)

이미지파일을 등록하고 - 잘됩니다 - 근데 출력하기란 코너를 통하거나 다른 코너들 예를 들어 테마를 변경하거나 하다보면 정말 가끔 첨부된 이미지가 사라집니다.

![20140915_021238](https://cloud.githubusercontent.com/assets/8669920/4264762/6af48b02-3c32-11e4-96d7-b635536e123c.jpg)

정확히 말하면 var 폴더에 있는 업로드된 이미지가 사라지는건 아니구요
_var.php 에 저장된 $d['layout']['title_title_file'] = "logo.png"; 이미지파일의 내용이 없어지는거 같은데 사실 액션파일도 찾지못했습니다. ㅋ 어딨지... 하면서...ㅋ
가끔 새로고침을 하면 다음 이미지 처럼 이미지파일이 사라진다는...

![20140915_021422](https://cloud.githubusercontent.com/assets/8669920/4264768/aefbc694-3c32-11e4-8bb1-e359379e2d81.jpg)

아마도 아직 이쪽 부분이 완성되지 않아서 생기는 문제같은데
혹시나 해서 또 우선 올려봅니다. 

제가 말하고도 참 정리가 안되는 ... ㅜㅜ
좀 더 상세한 원인을 알아내면 또 올려드릴께요~ 

힘나는 한 주 시작하세요~~

**Comment by kieregh** [comment]
말씀하신 내용은 2.1.0 에서 아래와 같이 수정되었습니다.
https://github.com/kimsQ/rb/commit/acf89b8928cd146a1a8fbbf8f2359464517a881a
https://github.com/kimsQ/rb/commit/eabb04d8c6553a5a3463973730d67a03c79f56d5
