### ISSUE TITLE
킴스큐 관리모드 > 모듈패널 > 레이아웃 파일경로 표시 style 적용

### ISSUE THREAD

**Issue by won5572** [kimsQ/rb#209]
modules>layout>admin>main.php
132줄 class 추가가 필요합니다.

									<ol class="breadcrumb pull-left">
										<li class="breadcrumb-item">파일경로 :</li>
										<li class="breadcrumb-item">root</li>
										<li class="breadcrumb-item">layouts</li>
										<li class="breadcrumb-item"><?php echo $layout?></li>
										<li class="breadcrumb-item"><?php echo str_replace('/','</li><li class="active">',$etcfile)?></li>
									</ol>

**Comment by gitaeks** [comment]
네, 감사합니다. 
BS4의 경로 스타일을 적용했습니다.

https://getbootstrap.com/docs/4.1/components/breadcrumb/
