### ISSUE TITLE
9월 8일자 commit 적용 후 모바일 게시판 글 목록에서 사라져

### ISSUE THREAD

**Issue by gilbert21han** [kimsQ/rb#218]
9월 8일자 commint 적용 후에 게시판에 쓴 글이 모바일 모드에서 안나타납니다.
초기화 시키고 다시 설치하고 패치해도 마찬가지 입니다.

**Comment by gitaeks** [comment]
패치되었습니다. 적용해보시고 오류사항에 대해서 제보해주시면 바로 패치해 드리겠습니다.  모바일 게시판의 일부 기능은 기능 마무리 중입니다.
