### ISSUE TITLE
유튜브 동영상 링크를 입력하면, 편집창에는 나오나 보기창(view)에서 링크만 나타남

### ISSUE THREAD

**Issue by gilbert21han** [kimsQ/rb#220]
글쓰기할 때, 동영상링크 아이콘을 눌러 유튜브 동영상 링크를 입력하면, 편집창에는 나타나지만 글보기를 하면 링크만 표시됨

**Comment by gitaeks** [comment]
링크를 변환하는 서버인 http://embed.kimsq.com/debug  에 SSL이 미적용되어  https를 사용하는 경우,  링크를 변환하여 전달된 데이터를 받지 못해서 생긴 상황 입니다.

사이트를 http로 접속해 보시면 정상적으로 변환되시리라 생각됩니다.

9월 중순경에 kimsQ ebmed 서버에 SSL을 적용하도록 하겠습니다.

**Comment by gilbert21han** [comment]
유튜브는 잘 나오는데, AWS S3 스토리지에 올린 동영상(올릴 영상의 수가 많아서)을 링크 걸었는데 적용이 안 돼네요.
예전 버전에는 유저첨부 동영상 링크 옵션이 "관리메뉴>시스템>보안"에 있었는데, 이를 복원해 주시면 좋겠네요.
