### ISSUE TITLE
패치하고 나면, 스마트폰 크롬브라우저에서 첫페이지 열면 "목록구성중" 계속

### ISSUE THREAD

**Issue by gilbert21han** [kimsQ/rb#221]
3일전부터 패치하고 나서, 스마트폰 크롬브라우저에서 첫페이지 열면 "목록구성중" 계속 뜨고, 다음으로 안넘어 갑니다.  PC 에뮬레이터에서는 잘 나오는데, 제목을 클릭하면 내용이 나오지 않네요.

**Comment by gilbert21han** [comment]
9월 8일 16:22:43에 commit된 파일 중에 BBS모듈 bbs/themes/_mobile/rc-default/list.php 변경으로 인한 오류로 파악됩니다.  tortoiseGit을 설치하고, 뒤로 reset 깃명령을 이용해 하나씩 내려갔더니 9월 6일 09:48:28 commint버전에서는 정상동작합니다.   모바일 리스트 기능에서 목록이 나타나지 않고 무한 반복으로 "목록구성중"이 나오니, 다른 모바일 테스트를 할 수가 없네요.

**Comment by gilbert21han** [comment]
오늘(9/16) 수정버전을 패치하고, 테스트 해 보았습니다.  2개의 사이트(saramcy.kimsq.co.kr, powerpt.kimsq.co.kr)을 해 보았는데, 크롭 웹브라우저로 PC에서 하는 경우, 게시판의 목록 표출이 모두 정상적이었습니다.  관리자모듈 내에 PC에뮬레이터를 이용하면 모두 잘 동작했습니다.  PC에뮬레이터에서는 어제까지 스마트폰과 같은 현상이 있었으나 사라졌습니다.  어제는 잘되던 목록표출도 사진한장 추가하고 나면, "목록구성중"에서 무한루프를 도는 현상이 있었습니다.

스마트폰은 겔럭시 노트 에찌와 베가LTE(IM-A890S) 모델을 이용해서 자체 웹브라우저와 크롬으로 테스트 해 보았습니다.  베가LTE는 오늘 수정버전도 마찬가지 무한루프를 도는 현상이 2개의 브라우저  2개의 사이트에서 모두 발생하고 있으며, 삼성겔럭시 노트에찌는 크롬 브라우저에서는 무한루프를 도는데, 삼성전용 웹브라우저에서는 정상적으로 목록표출이 되고 있습니다.

**Comment by gilbert21han** [comment]
오늘 새로 프로젝트를 개설해서, 킴스큐를 깔고 이전 기능이 개선되었나 테스트해 보았는데, 처음에만 나오고 보기모드를 섬네일이나 박스형으로 변경하고 나서는 다시 첫페이지에서 "목록구성중" 화면으로 무한 반복하여 다시 브라우저를 종료하고 접속해도 해당 화면에서 같은 내용만 반복됩니다.

저에게서만 이런 현상이 있는 것인가요?  누구라도 모바일모드로 동작을 시켜 목록보기 변경만 하면 나타날 것 같은데...  이것 때문에 모바일모드에 대해 다른 분들에게 홈페이지 보라고 할 수가 없네요.

http://mbkq24.kimsq.co.kr 첫 페이지에서 현상이 나타납니다.   뷰어모드를 변경하면 PC에뮤레이터 크롬에서도 마찬가지 입니다.

**Comment by gitaeks** [comment]
스마폰 브라우저의 캐시를 삭제하시고 다시 시도해 보시기 바랍니다.

모바일 크롬의 경우 아래와 같이 이용해 보시기 바랍니다.
설정 > 개인정보보호 >  인터넷 사용기록 삭제
