### ISSUE TITLE
Admin-SSL 환경설정에서 http 포트 안내문이 잘못 출력됨

### ISSUE THREAD

**Issue by YJSoft** [kimsQ/rb#30]
![image](https://cloud.githubusercontent.com/assets/5893514/4429053/d054b0ac-45d9-11e4-95c1-20e3917490b9.png)

HTTP 포트 입력란 밑에 있어야 할 설명이 SSL 포트번호 밑에 있습니다.

**Comment by kieregh** [comment]
말씀해주신 이슈는 2.0.0 공식버전에서 수정되었습니다.

감사합니다.
