### ISSUE TITLE
파일을 편집한 후 저장 버튼을 클릭하면 실시간으로 사용자 페이지에 적용됩니다

### ISSUE THREAD

**Issue by kiminmug** [kimsQ/rb#34]
사이트 메뉴에서 수정하기는 있는데  상기 제목과 같이 저장버튼이 없어서 어떻게 수정하고 저장 
하는지 ..   제가 잘 몰라서 그런지는 몰라도  저장버튼을 찾기가 힘들어여

**Comment by kieregh** [comment]
사이트 > 메뉴 에서 특정 메뉴 클릭하면 관련 내용을 수정할 수 있는데요...
수정을 마친 후 저장을 하는 방법은 [속성변경] 버튼을 누르시면 됩니다. 
이 것이 저장버튼의 역할을 합니다.

감사합니다.
