### ISSUE TITLE
구글 크롬에서 로그인이 안됩니다.

### ISSUE THREAD

**Issue by yangheemin** [kimsQ/rb#4]
사용 환경
Chrome on Windows 8
버전 32.0.1700.102 m

사용 KimsQ 버전 : rb_2.0.0_20131204

설치후 파이어폭스나 인터넷 익스플로러에서는 로그인에 문제가 없었으나,
크롬에서 계속 로그인이 안됩니다.

**Comment by kieregh** [comment]
로그인시 비밀번호 관련해서 이슈가 많았는데요...현재 2.1.0 에서 모두 해결되었습니다.
