### ISSUE TITLE
2.0 글로벌화와 관련된 데이터베이스 이슈

### ISSUE THREAD

**Issue by taiji88** [kimsQ/rb#43]
현재 2.0 오픈베타 데이터베이스 필드명을 보면
한글을 소리나는대로 영문화해서 설계한 부분과 spell이 틀린 부분등 여러가지 수정해야할 부분이 많은것 같습니다. 이 부분은 국내에서는 괜찮을지 모르나 해외시장에서는 많은 잡음이 발생할 것으로 예상됩니다. 아래는 특정 테이블에 속한 필드와 관련된 부분입니다. (왼쪽은 잘못된 필드명, 오른쪽은 수정해도 될만한 필드명)

[ s_comment ]
singo => report
cync => syncronize

[ s_domain ]
isson  => is_child

[ s_friend ]
rel  => 어떤 필드인지 모르겠음

[ s_mbrcomp ]
comp_upte => comp_condition
comp_jongmok => comp_item
우편번호, 주소1, 주소2 필드길이 변경필요

[ s_mbrdata ]
sosok => position
smail    => 쓰이는 용도가 없음
is_paper  => 쓰이는 용도가 없음
전화번호1, 전화번호2 필드길이 변경필요
우편번호, 주소0, 주소1, 주소2 필드길이 변경필요

[ s_mbrsns ]
미투데이, 요즘 필드 없애야 함.

[ s_menu ]
isson => is_child

[ s_oneline ]
singo  => report

[ s_page ]
sosokmenu => position_menu

[ s_trackback ]
cync	  => syncronize

[ s_upload ]
cync	 => syncronize

[ s_xtralog ]
singo => report

2.0 이 국내에 한정되어 있다면 관련 이슈는 그다지 중요하지 않습니다. 그러나 국제화를 표방하고 국제적인 모습을 갖춘다고 하면 외국인들은 프레임워크의 가장 핵심부분중에 하나인 데이터베이스 설계부분에서 많이 당황할듯하여 노파심에 글을 남겨봅니다.

개인적으로 이 이슈에서 가장 중요하게 생각해야할 부분은 기존 사용자들과의 호환성 문제라 생각합니다. 제 생각으로는 호환성에서 많은 문제가 된다고 하면 현재 구조 그대로 가지고 가시되, 국제화 관련 버전은 아예 필드명을 국제화 표준에 맞게 가저가시고 버전을 달리 하셔도 좋을듯 하네요.

관련 이슈에 많은 사용자분들의 의견이 있었으면 좋겠습니다. 감사합니다.

**Comment by kieregh** [comment]
요청하신 필드명 개선작업은 2.0.0 에서 일부 진행되었습니다. 
당분간 추가 변경작업은 힘들 것으로 판단됩니다.
