### ISSUE TITLE
end switch중 visitercheck 관련 몇가지 사항

### ISSUE THREAD

**Issue by taiji88** [kimsQ/rb#44]
일단 spell이 틀린듯 합니다.
visiter 가 아니라 visitor~

또한 현재 내부키워드 관련 공격이 심심치 않게 발견되고 있는데요.
이 부분은 관련 switch에서 s_inkey table에 임의의 도메인주소를 insert시킵니다.
rb구조상 사용자 세션이 생성되게 되면 그 이후부터는 검색창에 검색을 하는 즉시 s_inkey table에 insert가 되며 이를 무한 반복시에는 당연히 무한히 데이터가 s_inkey table에 들어가게 됩니다.
관련 부분은 추천검색어, 실시간검색어에 영향을 주고 있으며 이를 통한 해킹도 가능하리라 생각합니다.

개인적인 소견으로는
세션이 형성되더라도 같은 아이피에서 들어오는 부분을 막아야 할듯 하고
http, https가 포함된 검색어는 유입즉시 차단시키는방법도 좋을듯 합니다. (아래 참고)

if ($_SESSION['mylog'.$s])
{
    getDbUpdate($table['s_counter'],'page=page+1','site='.$s." and date='".$date['today']."'");
    if ($_keyword && !strstr('[name][nic][id][term]',$where))
    {
               // 추가
        if (preg_match("/(http|https):\/\/(.*?)$/i", $_keyword)) {
            exit;
        }

.............

**Comment by kieregh** [comment]
우선 오타 이슈는 2.1.0 에서 아래와 같이 수정되었습니다. 
https://github.com/kimsQ/rb/commit/0e88cf988ca763da75f9a0630a0400422051ff58

보안관련 이슈는 '관찰중' 상태로 두겠습니다.
