### ISSUE TITLE
summernote 버그 (킴스큐 공식홈 제보)

### ISSUE THREAD

**Issue by taiji88** [kimsQ/rb#62]
summernote 및 포토셋 버그와 관련한 내용 입니다.
1. 포토셋에서 가로가 긴 이미지를 등록하면 첨부시 잘림현상 (아자맨님 제보)
   ![err1](https://cloud.githubusercontent.com/assets/4546736/4802416/97376e7c-5e43-11e4-9c7c-86f5cc62af23.JPG)

![err2](https://cloud.githubusercontent.com/assets/4546736/4802414/8ac6aefa-5e43-11e4-9a3c-63ccffc1a3a7.jpg)

그림에서 보듯 가로가 2,000 pixel인 이미지를 등록하고 에디더테 삽입 했는데 800x800으로 맞춰지고 사이드가 전부 잘립니다.
1. 포토셋에서 이미지 등록후 오른쪽에서 '2장'선택한다음 삽입을 하면 아래 그림과 같이 이미지가 표시 안됨. (자체 제보)
   ![err3](https://cloud.githubusercontent.com/assets/4546736/4802441/f2a2de7c-5e43-11e4-9d36-9dd32225ab77.JPG)
2. 글자크기 버그 (oilugi님 제보)
   이 부분은 summernote 자체버그 입니다.
   글자 입력후 글자 일정부분 선택후 글자크기를 변경하면 선택한 한줄이 모두 크기가 변경됩니다.

**Comment by kieregh** [comment]
summernote 역시 별도의 오픈소스 프로젝트인만큼 최대한 해당 커뮤니티의 버그/처리 부분을 활용해야 할 것 같습니다. 지속적인 모니터링이 필요한 것 같습니다.
