### ISSUE TITLE
password_hash  PASSWORD_DEFAULT 사용시

### ISSUE THREAD

**Issue by iBNeer** [kimsQ/rb#65]
2.0 설치 완료처리될때 빈화면이 뜨길래 세션을 날리고 접속해보니 로그인이 안되는 현상이 있어서 확인해보았습니다.

password_hash 를 PASSWORD_DEFAULT 로 사용하면 시간에 따라 리턴을 해준다고 설명이 되있습니다.

마찬가지로 서버에서 getCrypt() 함수를 통하여 리플래시 하면 계속 값이 변경되어 뜹니다

**Comment by kieregh** [comment]
본 이슈는 아래의 링크를 참조하며 클로징하겠습니다.
https://github.com/kimsQ/rb/issues/68
