### ISSUE TITLE
외국 서버라서 그런지 ...

### ISSUE THREAD

**Issue by evangeliopleno** [kimsQ/rb#67]
직접 서버에서 다운로드 방식으로 해도 안 되고
업로드 형식으로 하면 업로드는 되는 것 같은데, 설치 버튼을 누르면 다시 서버에서 다운로드 한다는 메시지가 나오고 똑같이 아래 메시지가 나옵니다.

500 Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.
Please contact the server administrator at webmaster@xxxxxx to inform them of the time this error occurred, and the actions you performed just before this error.
More information about this error may be available in the server error log.
Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

그리고 IE 10에서 파일 업로드 방식을 선택하면 아래처럼 메시지 뜨고 넘어가지를 않습니다. 적어도 크롬은 다음 화면(위의 에러)으로 넘어갑니다.
![rb-001](https://cloud.githubusercontent.com/assets/9579465/4926986/cc2a525c-6537-11e4-8b17-610a2dfce953.jpg)

**Comment by kieregh** [comment]
제기하신 현상은 원인파악을 위해 좀더 관찰이 필요합니다.
