### ISSUE TITLE
getCrypt 함수 버그 입니다.

### ISSUE THREAD

**Issue by taiji88** [kimsQ/rb#68]
/_core/function/sys.func.php (getCrypt function)

if ($ver1[0] > 5 || ($ver1[1] > 4 && $ver1[1] > 4))
 {
 if(function_exists('password_hash')) return password_hash($str.$salt,PASSWORD_DEFAULT).'$1';
 }
 if ($ver1[0] > 5 || ($ver1[1] > 0 && $ver1[1] > 1))
 {
 if (in_array('sha512',hash_algos())) return hash('sha512',$str.$salt).'$2';
 else if (in_array('sha256',hash_algos())) return hash('sha256',$str.$salt).'$3';
 }

여기에서 
위 아래 if절 모두
if ($ver1[0] > 5 || ($ver1[1] > 4 && $ver1[1].... 부분요.
=> if ($ver1[0] > 5 || ($ver1[1] > 4 && $ver1[2].... 이렇게 되어야 할듯요.

아마 복사하시다가 잘못 하신듯 ㅎ
암호화 관련된 부분이라 최대한 빨리 패치하셔야 할듯 합니다.

**Comment by kieregh** [comment]
해당 함수는 아래와 같이 최종 수정되었습니다.
https://github.com/kimsQ/rb/blob/release-2.1.0/_core/function/sys.func.php
