### ISSUE TITLE
LICENSE와 LICENSE-DEFAULT의 차이

### ISSUE THREAD

**Issue by taiji88** [kimsQ/rb#71]
LICENSE파일은 영문이며 LGPL2.1
LICENSE-DEFAULT파일은 한글이며 LGPL3.0

두 라이선스가 맞지 않는거 같습니다.
하나로 통일되어야 하지 않을까해서 이슈에 올려봅니다.

**Comment by kieregh** [comment]
2.1.0 에서 아래와 같이 라이센스가 변경되었습니다.
https://github.com/kimsQ/rb/commit/20ae00c2be7335bca6c12c0e9576f2c631b80a42
