### ISSUE TITLE
설치하면서 에러가 뜹니다.

### ISSUE THREAD

**Issue by aalloorz** [kimsQ/rb#79]
![2222](https://cloud.githubusercontent.com/assets/9428733/5043479/e22ab5a4-6c28-11e4-9085-26064a646634.PNG)
![2222222223](https://cloud.githubusercontent.com/assets/9428733/5043482/e7efe086-6c28-11e4-871b-7cac6444aa50.PNG)

설치하면서 에러가 뜨는데요.
어떻게 해야 하나요? ㅎㅎ

**Comment by kieregh** [comment]
설치관련 이슌느 다양한 서버환경에 따라 다양하게 나타나고 있는만큼 지속적으로 관련 자료 및
테스트를 통해서 개선해나가도록 하겠습니다.
