### ISSUE TITLE
알림을 퀵패널로 설정했을 때 

### ISSUE THREAD

**Issue by fm3647** [kimsQ/rb#81]
![aaa](https://cloud.githubusercontent.com/assets/2323264/5110907/a4206d04-705f-11e4-8c8d-1817a82f503c.jpg)
알림을 퀵패널로 설정했을 때 알림 밑에 서브 메뉴이름이 보이지 않습니다.

**Comment by gitaeks** [comment]
본 이슈는 v2.1.0에서 패치 되었습니다.
