### ISSUE TITLE
부관리자 권한 문제

### ISSUE THREAD

**Issue by dobiz** [kimsQ/rb#88]
시스템도구 > 사용자 > '관리자 추가' 기능을 이용해 부관리자를 생성후 테스트하던 중 권한 문제가 있어서 이슈로 등록합니다.

1)  '시스템도구 접근제한' 상태에서 시스템도구로 접속 가능

① 주소 직접연결시 시스템도구로 진입
/?r=home&m=admin&module=admin&front=main

② 모듈관리 페이지에서 시스템도구 모듈 아이콘 클릭으로 시스템도구 진입

③ 관리제한 설정에서 '사이트'의 접근을 제한했을 경우 홈페이지보기에서 더블클릭후 '관리자모드 보기' 클릭시 '접근권한이 없습니다'라는 경고창이 나타난 뒤 시스템도구로 진입

위 3가지 모두 진입 이후 시스템도구의 설정값도 변경 가능합니다.

2) 부관리자가 최고관리자 정보를 변경 가능

위 방법으로 시스템도구 > 사용자 정보관리에서 최고관리자의 정보를 임의로 변경가능합니다. (비밀번호 포함)

**Comment by kieregh** [comment]
2.1.0 에서 아래와 같이 수정되었습니다.
https://github.com/kimsQ/rb/commit/4cd451fd96a6848fd2a726155d53031b47bce4ee
