### ISSUE TITLE
2.0 설치후 로그인이 안되요!!

### ISSUE THREAD

**Issue by taiji9203** [kimsQ/rb#89]
kimsQ/rb 2.0 설치후 관리자 로그인이 안되요!!
서버를 초기화 시키고 다시 설치하고를 반복해도 똑같은 증상이네요 ㅠㅠ

![id](https://cloud.githubusercontent.com/assets/10042058/5257923/64fad05e-7a25-11e4-9e06-0610fb03df58.jpg)
존재하지 않는 아이디라고 나옵니다..

PHP4, MySQL5.x

**Comment by kieregh** [comment]
2.1.0 릴리즈에서 로그인 관련 버그는 아래와 같이 수정되었습니다.
https://github.com/kimsQ/rb/commit/c5457217f146faf383fe7ff557163b0377441c57
