### ISSUE TITLE
어드민>사이트>페이지 ===> 키워드 검색시 검색버튼 누락 

### ISSUE THREAD

**Issue by kieregh** [kimsQ/rb#92]
modules/site/admin/page.php  79 Line....

<현재> 
<pre>
&lt;div class="rb-keyword-search">
  &lt;input type="text" name="keyw" class="form-control" value="&lt;?php echo $keyw?>" placeholder="&lt;?php echo _LANG('a3005','site')?>">
&lt;/div>
</pre>

<수정 제안>
<pre>
&lt;div class="rb-keyword-search input-group input-group-sm">
  &lt;input type="text" name="keyw" class="form-control" value="&lt;?php echo $keyw?>" placeholder="&lt;?
  php echo _LANG('a3005','site')?>">
  &lt;span class="input-group-btn">
     &lt;button class="btn btn-primary" type="submit">검색&lt;/button>
   &lt;/span>
&lt;/div>
</pre>

**Comment by gitaeks** [comment]
@kieregh 님,  pull request로 제출 요청 드립니다.

**Comment by kimsnova** [comment]
이것은 의도된 것입니다.
검색버튼 없이 키보드 엔터로 동작할 수 있습니다.
