### ISSUE TITLE
container_head(foot).engine.php  역할은 ?

### ISSUE THREAD

**Issue by kieregh** [kimsQ/rb#93]
2.0 에는 container_head.engine.php 과 container_foot.engine.php  이 없는데요...

2.0  코어에서는 각각의 모듈에서 정의한 header/footer 코드/이미지 들에 대한 노출을 지원하지
않는 것인가요? 

즉, 해당 부분은 해당 모듈에서 처리해야 하는건가요?

**Comment by kimsnova** [comment]
content.engine.php 에서 처리됩니다.
