### ISSUE TITLE
내장된 jQuery 플러그인의 기본버전 문제

### ISSUE THREAD

**Issue by BootstrapKR** [kimsQ/rb#96]
현재 Rb2에 기본 설치된 jQuery 버전이 2.0.3 인데요, 이것을 1.11.2 로 해주셔야 합니다.
아시다시피, jQuery 2.x는 IE6/7/8 을 지원하지 않기 때문에 해당 브라우저에서 각종 JS 오류가 발생하여 기능이 정상동작 안하는 경우가 많습니다.

IE6과 7은 몰라도, IE8은 아직 버리기 어렵습니다. (기본 레이아웃에서도 지원하는 버전이듯...)
또한, 플랫폼에서는 최신 버전보다는 보다 안정되고 폭넓은 버전을 기본값으로 해야 할것으로 보입니다. 모듈이나 레이아웃 개발자의 경우도 마찬가지일 것이구요.

실제로, 모듈에서 팝업윈도우를 띄워야 하는 경우가 있었는데, _blank 레이아웃에서 jQuery 2.0.3을 로드하여 Ie8에서 문제가 발생하더군요. 레이아웃이야, 자신이 원하는 버전을 내장시켜 처리할 수 있겠지만 모듈이나 이에 소속된 팝업 등은 속수무책인듯 합니다.

저같은 경우는, Rb2에 1.11.2 버전 설치하고 기본버전으로 설정하여 해결했지만... 사용자들에게 이 모듈을 사용하려면 jQuery 1.x 버전을 설치하고 기본 버전으로 설정하라고 말하기는 어려울 것입니다.

추가적으로, 사이트 주인장이 원한다면 2.x 를 사용할 수도 있고, 1.x도 사용할 수도 있는 기능은 정말 유연하고 좋습니다. 다만, 이러한 설정에 따라 많은 확장 모듈 등에서 호환성 문제가 꽤 발생할 수도 있다는 점도 고려해야 할 듯 합니다. Bootstrap이나 나머지 플러그인의 기본 버전에 대해서 한번 더 검토가 필요하지 않나 싶구요. 가이드라인도 필요할 듯 하고 그러네요...^^

결론적으로, Rb2 플랫폼 차원에서는 IE8 이상에서 정상 동작하도록 이것을 최소 사양으로 잡았으면 좋겠습니다.

이상 참고해 주세요~!

**Comment by gitaeks** [comment]
확인했습니다.

**Comment by gitaeks** [comment]
@BootstrapKR 님,  jQuery 1.11.2 버전을 플러그인 형태로  공식저장소에 pull request 요청드리겟습니다.

**Comment by BootstrapKR** [comment]
Pull Request 완료했습니다.

**Comment by kieregh** [comment]
2.1.0 릴리즈에서 아래와 같이 수정되었습니다.
https://github.com/kimsQ/rb/commit/2a64a538dafbc78cfa2f7c982a04a4cbe695777c
